// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
	detail?: Array<ValidationError>;
};

export type PingList = {
	page: number;
	pageSize: number;
	totalPages: number;
	results: Array<PingResponse>;
};

export type PingRequest = {
	data: string;
};

export type PingResponse = {
	id: string;
	data: string;
	timestamp: string;
};

export type SortDirection = "asc" | "desc";

export type ValidationError = {
	loc: Array<string | number>;
	msg: string;
	type: string;
};

export type GetPingsData = {
	body?: never;
	path?: never;
	query?: {
		page?: number;
		page_size?: number;
		sort_direction?: SortDirection;
	};
	url: "/api/ping/";
};

export type GetPingsErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type GetPingsError = GetPingsErrors[keyof GetPingsErrors];

export type GetPingsResponses = {
	/**
	 * Successful Response
	 */
	200: PingList;
};

export type GetPingsResponse = GetPingsResponses[keyof GetPingsResponses];

export type PingData = {
	body: PingRequest;
	path?: never;
	query?: never;
	url: "/api/ping/";
};

export type PingErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type PingError = PingErrors[keyof PingErrors];

export type PingResponses = {
	/**
	 * Successful Response
	 */
	200: PingResponse;
};

export type PingResponse2 = PingResponses[keyof PingResponses];

export type ClientOptions = {
	baseURL: "http://localhost:4173" | (string & {});
};
